---
title: "Consumo 20%, SGRc y FCRc"
author: "Pedro Pizarro"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(datasets)
library(ggplot2)
library(readxl)
library(tidyr)
library(dplyr)
library(lme4)
library(graphics)
library(stats)
library(stringr)
```

```{r}

BDatos_mod <- BDatos_mod %>% mutate (ID_Centro= substr(BDatos$Centro,1,3))
BDatos_mod <-BDatos_mod [, c(1,2,6,3,4,5)]
Id_Centro <- BDatos_mod$ID_Centro
BDatos_mod$ID_Centro <- as.factor(BDatos_mod$ID_Centro)
summary (BDatos_mod)
  
rm(BDatos_2)
rm(BDatos_mod)
rm(BDatos_2)
rm(BDatos_mod1)
```

```{r}
BDatos_2 <- str_replace(BDatos$Centro, "Elena Norte", "ElN")

```

```{r}
BDatos_mod <- BDatos_mod %>% mutate (ID_Centro = str_replace(Centro, "Elena Norte", "ElN"))
BDatos_mod$ID_Centro <- str_replace(BDatos_mod$ID_Centro, "Elena Weste", "ElW")

```

```{r}
BDatos_mod <- BDatos_mod %>% mutate (ID_Centro_2= substr(BDatos_mod$ID_Centro,1,3))
BDatos_mod <-BDatos_mod [, c(1,2,7,3,4,5,6)]
BDatos_mod$ID_Centro_2 <- as.factor(BDatos_mod$ID_Centro_2)
summary (BDatos_mod)
```


