---
title: Consumo de alimento en salmones bajo 20% de actividad y su relaci칩n con FCRc
  y SGRc
author: "Pedro Pizarro"
date: "`r Sys.Date()`"
output:
  beamer_presentation: default
  ioslides_presentation: default
theme: Antibes
colortheme: beaver
fonttheme: structurebold
includes:in_header: mystyle.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(datasets)
library(ggplot2)
library(readxl)
library(tidyr)
library(dplyr)
library(graphics)
library(stats)
library(stringr)
library(gridExtra)
library(knitr)
library(summarytools)
library(stats)
library(psych)
library(pander)
library(car)
library(lmtest)
library(lme4)
library(readxl)
library(ggplot2)
library(dplyr)
library(psych)
library(car)
library(nlme)
library(lme4)
library(readr)
library(lmtest)
library(sjPlot)
library(multcomp)
library(kableExtra)

```

## Introducci칩n

fgkggnlghknhknhk,nkb,,.,n,-,mnglbnlghgh,hlh,침l

hkkhlkgkhlkl [^1]

 [^1]: ammamaam
 
## Tablas

```{r}

```


## Gr치ficos

```{r}

```
## Iamgen



```{r}

```



