---
title: "Consumo 20%, SGRc y FCRc"
author: "Pedro Pizarro"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(datasets)
library(ggplot2)
library(readxl)
library(tidyr)
library(dplyr)
library(lme4)
library(graphics)
library(stats)
```

```{r}
read_excel("Base_Datos_Cons_FCR_SGR.xlsx")
BDatos <-read_excel("Base_Datos_Cons_FCR_SGR.xlsx")
```
```{r}
summary(BDatos)
```
```{r}
BDatos$Año <- as.factor(BDatos$Año)
BDatos$`Fecha_cosecha` <- as.factor(BDatos$`Fecha_cosecha`)
BDatos$Jaula <-as.factor(BDatos$Jaula)
BDatos$Centro <- as.factor(BDatos$Centro)
summary(BDatos)
str(BDatos)
```

```{r}
plot (density(BDatos$`Consumo Bajo 20 actividad`))
plot (density(BDatos$FCRc))
plot (density(BDatos$SGRc))

```

```{r}
plot (ecdf(BDatos$`Consumo Bajo 20 actividad`))
plot (ecdf(BDatos$FCRc))
plot (ecdf(BDatos$SGRc))
```

```{r}
Mi_gráfico = theme(axis.title.x = element_text(size = 16), axis.text.x = element_text(size = 12), axis.title.y = element_text(size = 16), axis.text.y = element_text(size = 12))
```

```{r}
ggplot(BDatos, aes(`Consumo Bajo 20 actividad`))+theme_gray()+
  geom_histogram(bins = 15, color= "black",fill="light blue")+
  labs(title="Histograma Consumo bajo 20% actividad", x="Consumo bajo 20% actividad", 
       y="Frecuencia")+ Mi_gráfico
```

```{r}
ggplot(BDatos, aes(FCRc))+theme_gray()+
  geom_histogram(bins = 15, color= "black",fill="light green")+
  labs(title="Histograma FCRc", x="FRCc (conversión)",y="Frecuencia")+ Mi_gráfico
```


```{r}
ggplot(BDatos, aes(SGRc))+theme_gray()+
  geom_histogram(bins = 15, color= "black",fill="light yellow")+
  labs(title="Histograma SGRc", x="SGRc (crecimiento)", 
       y="Frecuencia")+ Mi_gráfico
```


```{r}
BDatos_mod %>% select (Año, Centro, Consumo_20, FCRc_porc,SGRc_porc)
BDatos_imp <- BDatos_mod %>% select (Año, Centro, Consumo_20, FCRc_porc,SGRc_porc)
summary(BDatos_imp)
str(BDatos_imp)
```
```{r}
ggplot(BDatos_imp , aes(x= Centro , y=FCRc_porc , fill= Centro)) +
    geom_boxplot(color= "brown") + labs( x="Centro de cultivo" , y="FCRc")+ Mi_gráfico
```

```{r}
ggplot(BDatos_imp , aes(x=Centro , y=FCRc_porc ,fill=Centro)) +
    geom_boxplot(color= "brown") + labs( x="Centro de cultivo" , y="FCRc")+ Mi_gráfico
```

```{r}
ggplot(BDatos_imp , aes(x= Consumo_20 , y=FCRc_porc)) +
    geom_point(color= "brown") + labs( x="Consumo bajo 20% actividad" , y="FCRc")+ Mi_gráfico
```

```{r}
ggplot(BDatos_imp , aes(x= Consumo_20 , y=SGRc_porc)) +
    geom_point (color= "brown") + labs( x="Consumo bajo 20% actividad" , y="SGRc")+ Mi_gráfico
```
```{r}
BDatos_imp %>% group_by(Centro) %>% summarise(Consumo_prom = mean(Consumo_20), FCRc_prom = mean(FCRc_porc), SGRc_prom =mean(SGRc_porc))
```
```{r}
BDatos_gcentro <- BDatos_imp %>% group_by(Centro) %>% summarise(Consumo_prom = mean(Consumo_20), FCRc_prom = mean(FCRc_porc), SGRc_prom =mean(SGRc_porc)) %>% arrange(-Consumo_prom)
```

```{r}
BDatos_imp %>% group_by(Año,Centro) %>% summarise(Consumo_prom = mean(Consumo_20), FCRc_prom = mean(FCRc_porc), SGRc_prom =mean(SGRc_porc)) %>% arrange(-Consumo_prom)
```
```{r}
BDatos_imp %>% group_by(Año,Centro) %>% summarise(Consumo_prom = mean(Consumo_20), FCRc_prom = mean(FCRc_porc), SGRc_prom =mean(SGRc_porc)) %>% arrange(-Consumo_prom) %>% filter(Consumo_prom > 12)
```

```{r}
BDatos_top <- BDatos_imp %>% group_by(Año,Centro) %>% summarise(Consumo_prom = mean(Consumo_20), FCRc_prom = mean(FCRc_porc), SGRc_prom =mean(SGRc_porc)) %>% arrange(-Consumo_prom) %>% filter(Consumo_prom > 12)
```
```{r}
head(BDatos_top)
```


```{r}
Consumo_20 <- BDatos_imp$Consumo_20
FCRc_porc <- BDatos_imp$FCRc_porc
SGRc_porc <- BDatos_imp$SGRc_porc
```

```{r}
 ggplot(BDatos_imp , aes(x= Consumo_20 , y=FCRc_porc))+ geom_smooth(method = "lm", se= TRUE, color= "black")  + Mi_gráfico
```

```{r}
 ggplot(BDatos_imp , aes(x= Consumo_20 , y=SGRc_porc))+ geom_smooth(method = "lm", se= TRUE, color= "black")  + Mi_gráfico
```


```{r}
cor(BDatos_gcentro$Consumo_prom , BDatos_gcentro$FCRc_prom)
cor(BDatos_gcentro$Consumo_prom , BDatos_gcentro$SGRc_prom)
```
```{r}
cor(Consumo_20 , FCRc_porc)
cor(Consumo_20 , SGRc_porc)
```
```{r}
head(BDatos_top)
```

```{r}
head(BDatos_top)
cor(BDatos_top$Consumo_prom , BDatos_top$FCRc_prom)
cor(BDatos_top$Consumo_prom , BDatos_top$SGRc_prom)


```

