---
title: "Untitled"
author: "Pedro Pizarro"
date: '2022-06-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(datasets)
library(ggplot2)
library(readxl)
library(tidyr)
library(dplyr)
library(lme4)
library(graphics)
library(stats)
library(stringr)
library(gridExtra)
library(knitr)
library(summarytools)
library(stats)
library(psych)
library(pander)
library(car)
library(lmtest)
```


```{r}
 ggplot(BDatos_top , aes(x= Consumo20_prom , y=FCRc_prom))+ geom_smooth(method = "lm",  se= TRUE , color= "blue")+ geom_point(color= "blue") + Mi_gráfico
 ggplot(BDatos_top , aes(x= Consumo20_prom , y=SGRc_prom))+ geom_smooth(method = "lm",  se= TRUE , color= "blue")+ geom_point(color= "blue") + Mi_gráfico
```

```{r}
cor(BDatos_top$Consumo20_prom , BDatos_top$FCRc_prom)
cor(BDatos_top$Consumo20_prom , BDatos_top$SGRc_prom)
```

```{r}
 ggplot(BDatos_gcentro , aes(x= Consumo20_prom , y=FCRc_prom))+ geom_smooth(method = "lm",  se= TRUE , color= "blue")+ geom_point(color= "blue") + Mi_gráfico
 ggplot(BDatos_gcentro , aes(x= Consumo20_prom , y=SGRc_prom))+ geom_smooth(method = "lm",  se= TRUE , color= "blue")+ geom_point(color= "blue") + Mi_gráfico

```
```{r}
cor(BDatos_gcentro$Consumo20_prom , BDatos_gcentro$FCRc_prom)    
cor(BDatos_gcentro$Consumo20_prom , BDatos_gcentro$SGRc_prom)
```

```{r anova1 FCRc}
Lineal <- lm(FCRc_porc ~ Consumo_20 + Centro , data=BDatos_mod)
anova(Lineal)

```

```{r}
anova(Lineal)
summary(Lineal)

```


```{r}
plot(Lineal$residuals, pch=20, col = "blue",
cex.lab=1.25, cex.axis=1.25)
```
## Evaluación de supuestos

## Independencia de las muestras

```{r}
dwtest(FCRc_porc ~ Consumo_20 + Centro, data=BDatos_mod, alternative = c("two.sided"), iterations = 15)
dwtest(Lineal)
```
## Homogeneidad de las varianzas


```{r}
#leveneTest(FCRc_porc ~ Consumo_20 + Centro , data = BDatos_mod, center = "median")
#leveneTest(Lineal)



bptest(Lineal)
plot(Lineal, 1, pch=20, col = "blue",
cex.lab=1.5, cex.axis=1.5, sub = "")

```
## Normalidad


```{r}

#shapiro.test(Lineal)
qqPlot(Lineal)
plot(Lineal, 2, pch=20, col = "blue")

```









```{r}
 ggplot(BDatos_mod_2 , aes(x= Centro , y=FCRc_porc, color = Centro))+ geom_smooth(method = "lm", formula= "y~x", se= TRUE , color= "blue")+ geom_point() + Mi_gráfico_2
       
```

```{r}

```

